# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=linux32_debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),linux32_debug)
  jchat_server_config = linux32_debug
  jchat_client_config = linux32_debug
endif
ifeq ($(config),linux64_debug)
  jchat_server_config = linux64_debug
  jchat_client_config = linux64_debug
endif
ifeq ($(config),osx32_debug)
  jchat_server_config = osx32_debug
  jchat_client_config = osx32_debug
endif
ifeq ($(config),osx64_debug)
  jchat_server_config = osx64_debug
  jchat_client_config = osx64_debug
endif
ifeq ($(config),win32_debug)
  jchat_server_config = win32_debug
  jchat_client_config = win32_debug
endif
ifeq ($(config),win64_debug)
  jchat_server_config = win64_debug
  jchat_client_config = win64_debug
endif
ifeq ($(config),linux32_release)
  jchat_server_config = linux32_release
  jchat_client_config = linux32_release
endif
ifeq ($(config),linux64_release)
  jchat_server_config = linux64_release
  jchat_client_config = linux64_release
endif
ifeq ($(config),osx32_release)
  jchat_server_config = osx32_release
  jchat_client_config = osx32_release
endif
ifeq ($(config),osx64_release)
  jchat_server_config = osx64_release
  jchat_client_config = osx64_release
endif
ifeq ($(config),win32_release)
  jchat_server_config = win32_release
  jchat_client_config = win32_release
endif
ifeq ($(config),win64_release)
  jchat_server_config = win64_release
  jchat_client_config = win64_release
endif

PROJECTS := jchat_server jchat_client

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

jchat_server:
ifneq (,$(jchat_server_config))
	@echo "==== Building jchat_server ($(jchat_server_config)) ===="
	@${MAKE} --no-print-directory -C . -f jchat_server.make config=$(jchat_server_config)
endif

jchat_client:
ifneq (,$(jchat_client_config))
	@echo "==== Building jchat_client ($(jchat_client_config)) ===="
	@${MAKE} --no-print-directory -C . -f jchat_client.make config=$(jchat_client_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f jchat_server.make clean
	@${MAKE} --no-print-directory -C . -f jchat_client.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  linux32_debug"
	@echo "  linux64_debug"
	@echo "  osx32_debug"
	@echo "  osx64_debug"
	@echo "  win32_debug"
	@echo "  win64_debug"
	@echo "  linux32_release"
	@echo "  linux64_release"
	@echo "  osx32_release"
	@echo "  osx64_release"
	@echo "  win32_release"
	@echo "  win64_release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   jchat_server"
	@echo "   jchat_client"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"